//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace twMVC.Repositories.EF
{
    public partial class CustomerDemographics
    {
        #region Primitive Properties
    
        public virtual string CustomerTypeID
        {
            get;
            set;
        }
    
        public virtual string CustomerDesc
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Customers> Customers
        {
            get
            {
                if (_customers == null)
                {
                    var newCollection = new FixupCollection<Customers>();
                    newCollection.CollectionChanged += FixupCustomers;
                    _customers = newCollection;
                }
                return _customers;
            }
            set
            {
                if (!ReferenceEquals(_customers, value))
                {
                    var previousValue = _customers as FixupCollection<Customers>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomers;
                    }
                    _customers = value;
                    var newValue = value as FixupCollection<Customers>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomers;
                    }
                }
            }
        }
        private ICollection<Customers> _customers;

        #endregion

        #region Association Fixup
    
        private void FixupCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Customers item in e.NewItems)
                {
                    if (!item.CustomerDemographics.Contains(this))
                    {
                        item.CustomerDemographics.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customers item in e.OldItems)
                {
                    if (item.CustomerDemographics.Contains(this))
                    {
                        item.CustomerDemographics.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
