//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace twMVC.Repositories.EF
{
    public partial class Employees
    {
        #region Primitive Properties
    
        public virtual int EmployeeID
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string TitleOfCourtesy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BirthDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> HireDate
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string Region
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string Country
        {
            get;
            set;
        }
    
        public virtual string HomePhone
        {
            get;
            set;
        }
    
        public virtual string Extension
        {
            get;
            set;
        }
    
        public virtual byte[] Photo
        {
            get;
            set;
        }
    
        public virtual string Notes
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ReportsTo
        {
            get { return _reportsTo; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reportsTo != value)
                    {
                        if (Employees2 != null && Employees2.EmployeeID != value)
                        {
                            Employees2 = null;
                        }
                        _reportsTo = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reportsTo;
    
        public virtual string PhotoPath
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Employees> Employees1
        {
            get
            {
                if (_employees1 == null)
                {
                    var newCollection = new FixupCollection<Employees>();
                    newCollection.CollectionChanged += FixupEmployees1;
                    _employees1 = newCollection;
                }
                return _employees1;
            }
            set
            {
                if (!ReferenceEquals(_employees1, value))
                {
                    var previousValue = _employees1 as FixupCollection<Employees>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEmployees1;
                    }
                    _employees1 = value;
                    var newValue = value as FixupCollection<Employees>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEmployees1;
                    }
                }
            }
        }
        private ICollection<Employees> _employees1;
    
        public virtual Employees Employees2
        {
            get { return _employees2; }
            set
            {
                if (!ReferenceEquals(_employees2, value))
                {
                    var previousValue = _employees2;
                    _employees2 = value;
                    FixupEmployees2(previousValue);
                }
            }
        }
        private Employees _employees2;
    
        public virtual ICollection<Orders> Orders
        {
            get
            {
                if (_orders == null)
                {
                    var newCollection = new FixupCollection<Orders>();
                    newCollection.CollectionChanged += FixupOrders;
                    _orders = newCollection;
                }
                return _orders;
            }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    var previousValue = _orders as FixupCollection<Orders>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOrders;
                    }
                    _orders = value;
                    var newValue = value as FixupCollection<Orders>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOrders;
                    }
                }
            }
        }
        private ICollection<Orders> _orders;
    
        public virtual ICollection<Territories> Territories
        {
            get
            {
                if (_territories == null)
                {
                    var newCollection = new FixupCollection<Territories>();
                    newCollection.CollectionChanged += FixupTerritories;
                    _territories = newCollection;
                }
                return _territories;
            }
            set
            {
                if (!ReferenceEquals(_territories, value))
                {
                    var previousValue = _territories as FixupCollection<Territories>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTerritories;
                    }
                    _territories = value;
                    var newValue = value as FixupCollection<Territories>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTerritories;
                    }
                }
            }
        }
        private ICollection<Territories> _territories;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupEmployees2(Employees previousValue)
        {
            if (previousValue != null && previousValue.Employees1.Contains(this))
            {
                previousValue.Employees1.Remove(this);
            }
    
            if (Employees2 != null)
            {
                if (!Employees2.Employees1.Contains(this))
                {
                    Employees2.Employees1.Add(this);
                }
                if (ReportsTo != Employees2.EmployeeID)
                {
                    ReportsTo = Employees2.EmployeeID;
                }
            }
            else if (!_settingFK)
            {
                ReportsTo = null;
            }
        }
    
        private void FixupEmployees1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Employees item in e.NewItems)
                {
                    item.Employees2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Employees item in e.OldItems)
                {
                    if (ReferenceEquals(item.Employees2, this))
                    {
                        item.Employees2 = null;
                    }
                }
            }
        }
    
        private void FixupOrders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Orders item in e.NewItems)
                {
                    item.Employees = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Orders item in e.OldItems)
                {
                    if (ReferenceEquals(item.Employees, this))
                    {
                        item.Employees = null;
                    }
                }
            }
        }
    
        private void FixupTerritories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Territories item in e.NewItems)
                {
                    if (!item.Employees.Contains(this))
                    {
                        item.Employees.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Territories item in e.OldItems)
                {
                    if (item.Employees.Contains(this))
                    {
                        item.Employees.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
