//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace twMVC.Repositories.EF
{
    public partial class Order_Details
    {
        #region Primitive Properties
    
        public virtual int OrderID
        {
            get { return _orderID; }
            set
            {
                if (_orderID != value)
                {
                    if (Orders != null && Orders.OrderID != value)
                    {
                        Orders = null;
                    }
                    _orderID = value;
                }
            }
        }
        private int _orderID;
    
        public virtual int ProductID
        {
            get { return _productID; }
            set
            {
                if (_productID != value)
                {
                    if (Products != null && Products.ProductID != value)
                    {
                        Products = null;
                    }
                    _productID = value;
                }
            }
        }
        private int _productID;
    
        public virtual decimal UnitPrice
        {
            get;
            set;
        }
    
        public virtual short Quantity
        {
            get;
            set;
        }
    
        public virtual float Discount
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Orders Orders
        {
            get { return _orders; }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    var previousValue = _orders;
                    _orders = value;
                    FixupOrders(previousValue);
                }
            }
        }
        private Orders _orders;
    
        public virtual Products Products
        {
            get { return _products; }
            set
            {
                if (!ReferenceEquals(_products, value))
                {
                    var previousValue = _products;
                    _products = value;
                    FixupProducts(previousValue);
                }
            }
        }
        private Products _products;

        #endregion

        #region Association Fixup
    
        private void FixupOrders(Orders previousValue)
        {
            if (previousValue != null && previousValue.Order_Details.Contains(this))
            {
                previousValue.Order_Details.Remove(this);
            }
    
            if (Orders != null)
            {
                if (!Orders.Order_Details.Contains(this))
                {
                    Orders.Order_Details.Add(this);
                }
                if (OrderID != Orders.OrderID)
                {
                    OrderID = Orders.OrderID;
                }
            }
        }
    
        private void FixupProducts(Products previousValue)
        {
            if (previousValue != null && previousValue.Order_Details.Contains(this))
            {
                previousValue.Order_Details.Remove(this);
            }
    
            if (Products != null)
            {
                if (!Products.Order_Details.Contains(this))
                {
                    Products.Order_Details.Add(this);
                }
                if (ProductID != Products.ProductID)
                {
                    ProductID = Products.ProductID;
                }
            }
        }

        #endregion

    }
}
